--- #YAML:1.0
name:                XML-Compile-SOAP
version:             2.13
abstract:            SOAP and WSDL, client side
license:             perl
author:              
    - Mark Overmeer
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Slurp:                   0
    Log::Report:                   0.26
    LWP:                           5.816
    Test::Deep:                    0.095
    Test::More:                    0.54
    Test::Pod:                     1.00
    Time::HiRes:                   0
    XML::Compile:                  1.14
    XML::Compile::Cache:           0.94
    XML::Compile::Tester:          0.05
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
