--- #YAML:1.0
name:               XML-Compile-SOAP
version:            2.20
abstract:           SOAP and WSDL, client side
author:
    - Mark Overmeer
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Slurp:          0
    Log::Report:          0.9
    LWP:                  5.816
    Test::Deep:           0.095
    Test::More:           0.54
    Time::HiRes:          0
    XML::Compile:         1.2
    XML::Compile::Cache:  0.98
    XML::Compile::Tester:  0.05
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
