--- #YAML:1.0
name:                XML-Compile-SOAP
version:             2.00_01
abstract:            SOAP and WSDL, client side
license:             perl
author:              
    - Mark Overmeer
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Log::Report:                   0.17
    LWP:                           5.803
    Test::Deep:                    0.095
    Test::More:                    0.54
    Test::Pod:                     1.00
    Time::HiRes:                   0
    XML::Compile:                  0.99
    XML::Compile::Cache:           0.14
    XML::Compile::Tester:          0.03
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
